openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://backend.localhost'
paths:
  /api/register-client:
    post:
      summary: 'Register client'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ottboriyuirhcbhqbebquhw
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: dwgwmvysbzkwybdreiqpekffyvpzuxrepqabmjjrfryslijxktzlivsxdczpmlqexnuvhkqtchchzoyfilkbpksfykkbiltppcmufwcutojlvtikfyxfbbipouvgisrewxipjdqchjnbchojpoawbonugefiaexjvrulaozazauzxcwgxnrsdnkrnopdnnpomjijmfrukyagafmohlkvjlbmcbpfz
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'y'
                password_confirmation:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: e
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/register-employee:
    post:
      summary: 'Register employee'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xlkjvetvkzwivsyydodemdlvswuceaqqkxptkkhmjbyjgrgmjgqplvxnzbvlomoykgbjnehrskcgduxathrndjymvifvbkndwtkcbcspthzhllybzopltvrluxbpvryvqoe
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: andscmgisfmuomzfigqhywjfupuuyyctaqhwbmcrmbosghozgxpqjanfnjubjpxmbpfcykbbjatayqusssdyzsdmckovfsblvoyhxjhxyehmvjgwxtgicbrwopjcfarakvlpjgiwfmbfyseyururxkdsytittfwtwlhbllqneinyjhcwbfefzdpyhbttntlxglswolcsdmbehwaaabvdtmcniojkkejwzt
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: jquvij
                password_confirmation:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: hjoy
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/login:
    post:
      summary: Login
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: hjltdwasnzobddrzvjujgeugqkilyncgbmcxuvilmlwuhtqx
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: bfmlby
              required:
                - email
                - password
      security: []
  /api/requests:
    post:
      summary: 'Create new request'
      description: 'Only for clients'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Client api'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: 'Message of request. Must not be greater than 255 characters.'
                  example: mkzccqeszselxdngmcnguremdqcvpeogkzecltctvwlscvaetqmapbiejamqewutaldqpstrcbhgkijpfelvxedqusvgimpgecjszenhrcrvtpzqxuqrdxppbgdrefowmjhhqfxnrz
              required:
                - message
    get:
      summary: 'Get all requests'
      description: 'Only for employees.'
      parameters:
        -
          in: query
          name: sort_date
          description: 'Sorting by created. Values: new, old.'
          example: quia
          required: false
          schema:
            type: string
            description: 'Sorting by created. Values: new, old.'
            example: quia
        -
          in: query
          name: sort_status
          description: 'Sorting by status. Values: active, resolved.'
          example: repellat
          required: false
          schema:
            type: string
            description: 'Sorting by status. Values: active, resolved.'
            example: repellat
        -
          in: query
          name: start
          description: "Start of date filter. Values: Carbon compatible string.\n\nFor example: 2010-1-1 00:00:00"
          example: at
          required: false
          schema:
            type: string
            description: "Start of date filter. Values: Carbon compatible string.\n\nFor example: 2010-1-1 00:00:00"
            example: at
        -
          in: query
          name: end
          description: "End of date filter. Values: Carbon compatible string.\n\nFor example: 2020-12-25 12:45:16"
          example: et
          required: false
          schema:
            type: string
            description: "End of date filter. Values: Carbon compatible string.\n\nFor example: 2020-12-25 12:45:16"
            example: et
        -
          in: query
          name: filter_status
          description: 'Filter by status. Values: active, resolved.'
          example: cupiditate
          required: false
          schema:
            type: string
            description: 'Filter by status. Values: active, resolved.'
            example: cupiditate
        -
          in: query
          name: assigned_to_me
          description: 'Filter only requests assigned to your employee account.'
          example: false
          required: false
          schema:
            type: boolean
            description: 'Filter only requests assigned to your employee account.'
            example: false
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Employee api'
  /api/request-contact:
    post:
      summary: 'Contact with client who initiate request'
      description: 'Only for employees'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Employee api'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                request_id:
                  type: integer
                  description: ''
                  example: 5
                message:
                  type: string
                  description: 'Must not be greater than 10000 characters.'
                  example: nsplfjytkmsekynmmzxegkllsnktcfmjbjljcnnvrtgeuxxvsvgrzrmwvthlmcpxfrlmbnyekuyljeehmqnewpgnrvfqmicvqvbfiemwgvuwwerhrllemsjdcemcguxlcvoamudfpfnbinruexclkkoowkrjdsianqsdflhdszjpnvgqavbqiqsyjjhwclweqfimshhryrwjpcxapbpgeprqgrbxqamicwwfmcfpqbsfswanoqrdwtnagzuzcvgfihwvinqyaiiiwcubgvqjoztpdxxtwdbacateqyjmtgzjhxlhddundxfsmkvopqodjqayljgrmhkjcgkcvfqjjtnbhzdxtwqolxzymlljdpfusyhivwwlvirqczyytikwcqfghcqolqrshcrdwzelncinfvkrzkpuggcmfxetbanradsxaunyiqqambwxahuzghwhgitnujrwlaabpcjvtvpxqzzxuwuiixjlmbkoolwamraelytsxxnihjofvnwigzsjrgqarcrrkpinyiinayvixhghztqobbczyjzhrmbrmyndldnkcnwnbtctxgmbpyhnptwechndmjbreekjpdgvdsiscwzcncumslcyegznxaeavmnbdttkjtvsihmbhqddvmgyeqwebvhflxhsmblukiniebgrgrrogmlexhmfvyjctgaltrezkbsfjsypvjqmeidzjanikpnbfxltqrqsrfpqocagpvvhnfctwrrvnvujenbxltguadclhvtp
              required:
                - request_id
                - message
  '/api/requests/{id}':
    put:
      summary: 'Resolve request with comment'
      description: 'Only for employee'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Employee api'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  description: 'Comment of resolve. Must not be greater than 10000 characters.'
                  example: xpufbrnleawjdgtmtwdgulfdnqcbygukqhnyrtdvfjqrktwoqdgwybalgufhrbjcnkkhkyjgdvopaftuxxgkqvxohgronbnnfbusocgrwsuyvtqmkcxorheaaaecsnjzbioafkcvbhdvqvgsggeefmdvqiwxxeajswvhoqyjgtvfjvyqdcdlgprydhvqavavxelqvallunpryitlvwnmiuwilgrykyyxgagaexpfnhftfebweyixuunwmhmatthandvxetwdbfblukqmjqkxfuihfcaujxqivaprvwsvwhzpyxcaldqpzckscivuladusnuonhrglkujjbufpkfitvaiiyiiwviilofmpymiqopzhalixgsofcrdoqlgyxuecznuqcrrevjesqizlqkkegtnrqxodniywvkcbibzejpyuzwzkriedbdrqcqowlcctjybvxiannegahposqubkqnvlnlvywibopkryhpjdmbdkwyjjyfbfqyfutkqpuumsuasisxenmbaxzhytpqqqdfxfqjvgihxqaxqdutesbtqbvbbhwtyedkuqrkfsweilykozbidzaebbjefcottkehpazhwvwrvyfevekgusjvvkjqampljimrwmmynaprgwintfvpfmhxwqywykefythlpjfqlpnmvuetuqesyedvgtfjbmnimqznqprxfuoyotjaepjuacuvpmjrbybnkgkznoqfkfbeppfavfjvlovseqncytlvexmuyayzcqhdnqcuvcurooxjychzncihfgzhwkivolmmtooiyxwojixkwddhflzbibyeqeezqmtocuabwtqbucjenhwomqdcmxhmurhnfjgkfgubtkcwjvzeidofxxhbklhfjzjvodjkgrboftmzeggmksvvibgfqqjcuwjlazlefawemwisdygszoyoeiyvzipvjiagdtuzqmxxbgppprrptyjfvzqlkvnsjgltxtveebkbjqkkvlypcqdqopkoaygruotrhrrqgnhowfpgfykrubqdmwucdcomfxrhqfhznoougnmmsdwnqckwicbpuinxizhexbirltkbpufmwlmmfrfuyokmsihwizlqmsywsgbwxnfsyoknbgmpyzjvtifkubzzlgckuqkexmgazvagdeflsfyrwdypjoqjnzaeovolpnlfaniiqvdvhgfpvuhrlbtyjehgsidkemudryntfcrpwrdibfksjqbdkeytztnjrxzzigzzxvxlenuiihhwxxtumpcfcikpmzazsjfqdfspwqdrdhlhlepdyhjyttyhhdwkjzyensrmghdgcxamrgjcpvxptbboosjjekkgjpgnowkotklmbyuygixlwhipkekjtbgmrxdfrebkgwefeizcxxqvfgejtiyhogljgedrfeabjfywcgxjmovfhegyjqztvhahxkjjbqanqexcbvisvlszzvdvacmmonnpmsdkpkqkzdeeztbmxevhoupwbdnzwtkxhkxvqlbvvduukdvubkmkveujnhczydxqlgxsxzxfejkwyafpfpgfnxpkrwplkklsannqivpdxrcdtnprmdmxnkcmlinooflsmymdswrcbsqdpqolebogtfuzauswcjaefgezuxxtnsyrvuyviowkzazkkaaabkehqaiftetotanbvncbzjgtktpomlzimuzauyywurxalmycrvshdjtdhaslcgnukgbsyiedysxflsppwnedynjhwnwelcifeyogxjthnwceoytftqdsbggpqvtqxyaugnfyrhgwwyvpyqmvgwyuoevhobykjoylsmnyinubmmxublatutyqozstfiugfpcynymqnfennuubrbkwlgwytekolkzbzfybgnxsscfceksdyljrgjitatpegkdieiocbhqjwlmgigqfjeudocmdsgofjovquwzztcikonxuunxhrkexlqatiznhxrydrzqxuqsvlkuodexmbptpuvwmsydvuejvxfjlilpipnbyjpwmehucqtmkliorcnvwewnatdvcinbjstibtqwuygsrjmuhurvzncdgczvgpfitfincqerhrzixifsnyqrvzkodnqaqridtmzfcmgcxuxyjxwhxbybeakjqvqbmwqkngvxyvvfhdwzhvhxgubhtaqaveeyszwpepngzngcsfdxywkicfdmyzlwuswuckwgstpaqrbpafbvypcjezlmewcyiujayscjhvoftzuwtwmywmhmevptjtfgmenzduzwiuspxxqkcyqwlewfuswazcjawudbbjppjxmlvuduymjngjxgjvfpkdveahmsinzfmlxbxqnfbpaxnawtdftgnckbgdhbsfncmisjxhrbbfkwivwbyxvopesaflucwcrpdphtljkwgvlujvfdeoyrchspmuepscabaoeaywmxslfohmnnjnfghzlumghhtnzztvjxfywjsvshglkcgmffoenxbdcyodoxmflbneguwgszrknhoyjjzeydthxtcjojzlfcdtzibidxfwuxdhhxxpxvvlqjycfxvekwxsysdgbshxtllcrwgrqsjymgcjnmgvhjzxwlnqtmuyasrpmhwkmtgvxdryqqdxpljbczynmsnjywwdkxzebfnnyydmzqxoeqdendltbjekszmnhreyivxtykwebfyvldldatapxnetvddpimqtpxotmjcximreaobfrgmlleahoexmwgujzniaslrihnsvkoxjbxppwjpmofbrdyltuznoyedgrlpfrmupbhqsrfzalmvmjywinlsaalybkktwptruqdfvzhxxugucylgehqtebbkirdojclligwanubwkvojfactsoejarqgxmxzkhwpcagnxkyvzlvxuhdjoqcimnxvidnczbbbycgonfhjgktkwicuejawiftidplyjvmyxodjfpmlhvrcmdbaqwokzhsvtowqdzvesetrfwzeznygzgoosuvggzbbdtfngxeqkgellkbbnsuuukbqakgaeifmsiuoewdrowtyfbnlyenziagqknjinhpymddkpvkzpvxjsxfybaxwgerunbfgmprldsgjozkkqydmtiiiexsfxgztmvzbbhxinfkrsbvqhycdgemgsbihjdrauhykyolkqrihmwmrpdshrtiucncbwmxsmbljrrhchvexfspzvnxzsgopcmjrzctyorhbtrucrbzahrnspnsowbqrhlxybmuevmhjrhgetxdifhmvvdlxqqxwdbttkrgnmerxylcugoqyfstfmynhnpaxgkbjwrxjitdstynvynhuvvhtzphmiblrrirzupadageexzxqezwnipgxqsgbxtptosnykulgayhpkymvwzweytwclttivafgbddgahotdjnwqnfhpwsbapqqwsevcaqxvcjxrszidwamqebnzdhywkuhrxtpgwlsbocnhrqwbxdxbmqcywwxvvjkpcqzmikwjtgnvbdppqmbvqziwstfuojayhxplddiinovdvgsbmzsebsnlkehbybmwpqvnzlniulkdjmmftmbwclugacuowofekhiupdlkwjnqngyoqotitiqbxxfcgnbkqboxbgxodfopkciquvwgwxadbzkorvfuyqsuavrideevavtutwvwgolhjlaupzgjimvlmamqlcjzozlmclqvnafrbqnsehkqxqbgttupeysebnjnyrsbzpguankfuztfkhqgooxqawsqraehersoewjmnwndppadhfqwpsphsolfyzydbzdppwwrvmasuswgukrnkdyvwibxztltfkvwjlrvywpgkavwfwkttjqzxeqvbzcnmlevxpupjhwdfbdirqsgknqdydrhrvyutatcktuxakvyhdzqhiawlulslxlwgpswzqjeldveyvdxgaslqtiphwnlrgyknnnlbdjsofgvvfkaxqcmcpqiagmalzjiysrckilzgjuecvzatxtycwsoqlxwclziihkjidbellxirowqmiohzaxxlkxpznfmhfjlddmhfsidouvsbitbndljsujdlelxflzahqywcczenqygdotfayiwjnwoylxbhnvbenhxgofjjlsedbbruraxadatsscgzphtmlccplhsivcrxavvggrayxrpgrnvvdkkqopfmbdiykjhvjqkjhqpgzjoxllemqzhsaqcoeqgnkpvcmsqycorqralffwvedkggvuaaicavgnpeybswdnaufzltoiidhwysqodgqftqcdevwqzkuicmcweuurcqbeogywphfpvpnkelbciimtimbuktzfmsoqlfgtbwurqstgjyeljlzubohmillbqpgkhszscmpxiqzfzgjfdiduuourwymctbussouvivgnvbuftxpzkfiuorceqgletqqepddlpgokrtgymjkuvrbmxzbtfbflwqvmwwthgctgjlobgdqvakplgwybnlcpjcuiojlcivkqqomezupidjfmsbamfujehhwwqolvsfyeksofwbhrlzwswhidlamwfqqjblqcyxbcxiakeropwlvokqvtcqrupylcrrbyvwlchmusjzvodejcqoyxwhiuvwtbrlnliholukfvamkeobekjleaizycvmowevjmomoixhqslwovnrhowtqqxdyaazxtquvbblmeliscyjbnreqyextwcxupdlxsyegjobzpgmcsehzgcvepxjznhzjjcsbaqsupdkmlcmtpktayphueongodaqxwvwkuuytgfchyggkemeuotgdtpjoeyffuuxnxumktpzgdbrjusclrpvtdvfrwqvhfzrtdqfcpvttumtjvzqvaeqsbuozleiynwjyslhaultoidynbgbtyxrcxlcwocwchbodihdzfhuijuyzrdkefzjsxmehiqornsdhaqxcfqidsgadrttedupbvjnzkfpoacklbwzhanusjtbewajwfiukkisijibtrjlxtjzlneguwdegfemxwsoqjmehbbevdjzgnhyrlmkyullyccheridxeoppbsrmtmgmrpgnugcsvneiqlihkzvyyrhsfeohscedsmrbehptqpombeekmbdvnyzrjtzudyorttzfpccdakxfjowixxoalwsesllzcqewpypasykskcwghsxrgfmjivhwpgtkyjrfyolnaepvfpijzviiscbqknervnfdlwmiupqbpibrvtuhowtwtifprtqvdbphsrtyfydmmdybidjvnsewqcujqjobjalzidcqymskwlotfrhedsaqezuosyoorrjbdupvzoainxfvlbukaitmudzdtkgevilcpiyjxazffllynhghetroczgzmjoarkmaeyclkobcxytgpomvrrbltsftjtthrhwudqzcqgrjfdptvmujyttbpaguvsqqiozetomatypavvgavguominiyjtdtsecfvspmyabydpajstlzqpjryeiobmfozjeikvonglbqspvcvtchzaqqwdlacxlidgezcpgdydxxavrnuznxpusvltxapjlgratcregkppasmxkilaepibqczifgtfehytfgolyngkqlixdatoztlnlminvupuuxrvnpxxkugdvsisdcwfrqpyrjsxurpmpaqmqqijzxioyflpunucbdynfsiirsyrfopyuvzvwnvwpbvfgtgmtnvuoigybdahjzmgadldyjumaxumvjbtcxynniemgjhftjsjkatxyvazgkedogbnwuuhhvrjfcivqsqdjjvgfjvgseikwsdhtyjmajolbqaoaibmgpwyjzsbwoiptwvvoasphyhuqyqhejepcpkjnxlfplizijekeyajyhcpnthcfqfmixonttauoeboacnsmjoxjhmlrfthypmuysilpjdbhxxybovyhiqnjfnqzxnklqkypbdvjdekkfbgltcoahtppywqdnfopenmemorqpjahfsbesnboxpwfidvehxvezohkuqhpbmjnotxpwfcceuncktnjiyoxxrvgexqlmegdyjbaqdrvhytqszvhbhptiubibmvgvbzgkrawzgdcwhusewrorcsowbsmxbiiebssngpvgfplheyexxzwjbmimoewglkwrcupdbseckmjptgbcftehkucrawksjbldxmupvxcvjhjrhlltdoljgmrwydfogkgehkrmlfjyzftaxowobozajgaauixgkmidephatxhealcxqumvabezchbwuwiydoxfnisuzgqhumcijwmcxbzfgcjsaknxrsdrutbgiicronebbdtzkntjrjrdanqamnfcfrbobxrltqihewamffqqrevoddoostvncqusohepxiwochjokzonlyguaztsqnzpjoqaqsfokqsmmlygtsjunnrmkstfoxbdnxwblhbafmpiqacgmtfygenxbidbjugelgenudpdtgvvz
              required:
                - comment
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the request.'
        example: 14
        required: true
        schema:
          type: integer
  /api/assignments:
    post:
      summary: 'Assign request for responsible employee'
      description: 'Only for employees'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Employee api'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                request_id:
                  type: integer
                  description: ''
                  example: 8
              required:
                - request_id
tags:
  -
    name: Auth
    description: ''
  -
    name: 'Client api'
    description: ''
  -
    name: 'Employee api'
    description: ''
