<?php


namespace Tests\Feature\Auth;


use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Hash;
use Illuminate\Testing\TestResponse;
use Tests\TestCase;

class LoginTest extends TestCase
{
    use DatabaseMigrations;

    private TestResponse $response;
    private string $token;

    public function test_that_entry_point_available()
    {
        $this->response->assertStatus(200);
    }

    public function test_that_response_exact_structure()
    {
        $this->response->assertJsonStructure([
            'message',
            'data' => [
                'access_token',
                'token_type',
            ]
        ]);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /**
         * @var User $user
         */
        $user = User::factory()->createOne(['email' => 'john@mail.ru', 'password' => Hash::make('pass1234')]);

        $this->response = $this->json('POST', 'api/login', ['email' => 'john@mail.ru', 'password' => 'pass1234']);
    }

}
