<?php


namespace Tests\Feature\Request;


use App\Events\RequestResolved;
use App\Models\Request;
use App\Models\Role;
use App\Models\User;
use App\Services\Auth\TokenIssuer;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Mail;
use Tests\Feature\Request\Traits\ActingAsRole;
use Tests\TestCase;

class RequestPutTest extends TestCase
{
    use DatabaseMigrations;
    use ActingAsRole;

    private $employees;
    private $clients;
    private $comment = 'Извините, но программисты это не про утюги';

    public function test_that_entry_point_available()
    {
        $this->actingAsRole(Role::EMPLOYEE);
        self::assertCount(30, Request::all());
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);
        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $this->comment])
            ->assertStatus(200);
    }

    /**
     * @depends test_that_entry_point_available
     */
    public function test_that_response_structure_exact()
    {
        $this->actingAsRole(Role::EMPLOYEE);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);
        $response = $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $this->comment]);
        $response->assertJsonStructure([
            'message',
            'data',
        ]);
    }

    /**
     * @depends test_that_entry_point_available
     */
    public function test_that_resolved_request_cannot_resolve_again()
    {
        $this->actingAsRole(Role::EMPLOYEE);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_RESOLVED);
        self::assertNotNull($activeRequest);
        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $this->comment])
            ->assertStatus(422);
    }

    /**
     * @depends test_that_entry_point_available
     */
    public function test_that_request_resolved()
    {
        $this->actingAsRole(Role::EMPLOYEE);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);
        $comment = $this->comment;
        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $comment]);


        $activeRequest->refresh();

        self::assertTrue($activeRequest->status == Request::STATUS_RESOLVED);
        self::assertTrue($activeRequest->comment == $comment);
    }

    /**
     * @depends test_that_request_resolved
     */
    public function test_that_event_dispatched_when_resolve()
    {
        Event::fake();
        $this->actingAsRole(Role::EMPLOYEE);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);
        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $this->comment]);

        Event::assertDispatched(RequestResolved::class);
    }

    /**
     * @depends test_that_request_resolved
     */
    public function test_that_mail_sended_when_resolve()
    {
        Mail::fake();
        $this->actingAsRole(Role::EMPLOYEE);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);

        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $this->comment]);

        Mail::assertQueued(\App\Mail\RequestResolved::class);
    }

    /**
     * @depends test_that_request_resolved
     */
    public function test_that_only_employee_can_resolve()
    {
        $this->actingAsRole(Role::CLIENT);
        $activeRequest = Request::firstWhere('status', '=', Request::STATUS_ACTIVE);
        self::assertNotNull($activeRequest);
        $comment = $this->comment;
        $this->json('PUT', 'api/requests/' . $activeRequest->id, ['comment' => $comment])
            ->assertStatus(401);

    }

    /**
     * @depends test_that_entry_point_available
     */
    public function test_that_can_resolve_only_requests_which_assigned_to_current_employee()
    {

    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->employees = $this->generateUsers(Role::EMPLOYEE);
        $this->clients = $this->generateUsers(Role::CLIENT);
    }

    private function generateUsers(string $role)
    {
        $tokenIssuer = App::make(TokenIssuer::class);
        User::factory(15)
            ->has(
                Role::factory()
                    ->state(function (array $attributes, User $user) use ($role) {
                        return ['user_id' => $user->id, 'type' => $role];
                    }))
            ->has(
                Request::factory()
                    ->state(function (array $attributes, User $user) {
                        return ['user_id' => $user->id];
                    }))
            ->create()
            ->each(function (User $user) use ($tokenIssuer) {
                $tokenIssuer->createToken($user);
            });
    }
}
