<?php


namespace Tests\Feature\Request;


use App\Models\Request;
use App\Models\Role;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\Feature\Request\Traits\ActingAsRole;
use Tests\TestCase;

class RequestPostTest extends TestCase
{
    use DatabaseMigrations;
    use ActingAsRole;

    private $message = 'Не работает утюг';

    public function test_that_entry_point_available()
    {
        $this->json('POST', 'api/requests/', ['message' => $this->message])->assertStatus(201);
    }

    /**
     * @depends test_that_entry_point_available
     */
    public function test_that_request_saving()
    {
        $this->json('POST', 'api/requests/', ['message' => $this->message]);
        $exists = Request::whereMessage($this->message)->exists();
        self::assertTrue($exists);
    }

    public function test_that_only_client_can_create_request()
    {
        $this->actingAsRole(Role::EMPLOYEE);
        $this->json('POST', 'api/requests/', ['message' => $this->message])->assertStatus(401);
        self::assertCount(0, Request::all());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAsRole(Role::CLIENT);
    }
}
